doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:           the9lands
                user:             cioumpy
                password:         syse85
                host:             localhost
                port:             3306
                server_version:   '8.0.19'
            rules:
                dbname:           t9l_ddrules
                user:             cioumpy
                password:         syse85
                host:             localhost
                port:             3306
                server_version:   '8.0.19'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
