version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./docker/the9lands/:/var/www/the9lands/
    ports:
      - 8001:80
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://cioumpy:5y5eZzOzBs@mysql:3306/the9lands?serverVersion=8.0
    volumes:
      - ./docker/the9lands/:/var/www/the9lands/
    networks:
      - symfony
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: ['--character-set-server=ytf8mb4','--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: the9lands
      MYSQL_USER: cioumpy
      MYSQL_PASSWORD: 5y5eZzOzBs
      MYSQL_ROOT_PASSWORD: 5y5eZzOzBs
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
